name: Generate README

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate README
        run: |
          echo "# My Project" > README.md
          echo "## Files" >> README.md
          for file in $(find . -name "*.md" | sed 's|^\./||'); do
            echo "- [$(basename "$file")](./$file)" >> README.md
          done
          
      - name: Commit changes
        run: |
          git config --local user.email "shilpat95@gmail.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README with file links" || echo "No changes to commit"
          git push
